spring:
  application:
    name: consumer
server:
  port: 8200
eureka:
  instance:
    prefer-ip-address: true #使用ip进行注册
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/